spring:
  datasource:
    url: jdbc:mysql://localhost:3306/donation?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Super@3abdou
    username: root
  jpa:
    hibernate.ddl-auto: update
  mvc:
    format:
      date-time: iso
  mail:
    host: smtp.gmail.com
    port: 587
    username: buyerbridge6@gmail.com
    password: igmo ardq sxzy ctld
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port : 8080

stripe:
  secret:
    key: sk_test_51PdVeuKpnFKx1MbZqEOxDXyayxlI1UNGECBC2GxUeiohsNpzg4NIIOucOFTDwzvAOtWH5KKZkbr8MLfJBI5M4lru00NFV3b8n4


springdoc:
  swagger-ui:
    operationsSorter: method